#!/bin/bash
git clone https://github.com/riqueenz/Free-CAD-config.git
git clone --branch FreeCAD-mechanical https://github.com/riqueenz/TabBar.git
git clone --branch FreeCAD-mechanical https://github.com/riqueenz/Glass.git
git clone https://github.com/shaise/FreeCAD_FastenersWB.git
git clone https://github.com/kbwbe/A2plus.git
git clone https://github.com/looooo/freecad.gears.git
git clone --branch FreeCAD-mechanical https://github.com/riqueenz/mooc-workbench.git

