#!/bin/bash
git clone --single-branch --branch FreeCAD-mechanical https://github.com/riqueenz/TabBar.git
git clone --single-branch --branch FreeCAD-mechanical https://github.com/riqueenz/Glass.git
git clone https://github.com/shaise/FreeCAD_FastenersWB.git
git clone https://github.com/kbwbe/A2plus.git
git clone https://github.com/looooo/freecad.gears.git
git clone --single-branch --branch FreeCAD-mechanical https://github.com/riqueenz/mooc-workbench.git
